---
kind: pipeline
type: kubernetes
name: crowdin
metadata:
  namespace: git
steps:
  - name: Update Translations
    image: crowdin/cli
    environment: 
      TOKEN:
        from_secret: crowdin_token
    commands:
      - crowdin upload -b main -T $TOKEN
      - crowdin pull -b main -T $TOKEN
  - name: Push changes
    image: node:current-bullseye
    environment: 
      TOKEN:
        from_secret: drone_gitea
    commands:
      - yarn install
      - yarn workspace @snort/app format
      - apt update && apt install git -y
      - git config --local user.email drone@v0l.io
      - git config --local user.name "Drone CI"
      - git remote set-url origin https://drone:$TOKEN@git.v0l.io/Kieran/snort.git
      - git diff
      - git switch -c lang
      - git commit -a -m "Update translations"
      - git push -u origin lang
---
kind: pipeline
type: kubernetes
name: docker
metadata:
  namespace: git
steps:
  - name: build docker image
    image: r.j3ss.co/img
    privileged: true
    volumes:
      - name: cache
        path: /docker-cache
    environment: 
      TOKEN:
        from_secret: img_token
    commands:
      - img login -u kieran -p $TOKEN git.v0l.io
      - |-
        img build -t git.v0l.io/kieran/snort:latest \
        --platform linux/amd64,linux/arm64 \
        --cache-from "type=local,src=/docker-cache" \
        --cache-to "type=local,dest=/docker-cache" \
        .
      - img push git.v0l.io/kieran/snort:latest
volumes:
- name: cache
  claim:
    name: docker-cache
---
kind: pipeline
type: kubernetes
name: test-lint
metadata:
  namespace: git
steps:
  - name: Test/Lint
    image: node:current-bullseye
    commands:
      - yarn install
      - yarn workspace @snort/nostr build
      - yarn workspace @snort/app test
      - yarn workspace @snort/app eslint
      - yarn workspace @snort/app prettier --check .